client
dev tun
proto udp

remote 10.1.3.2 1194

ca   /root/openvpn/client1/ca.crt
cert /root/openvpn/client1/client1.crt
key  /root/openvpn/client1/client1.key

remote-cert-tls server
persist-key
persist-tun
verb 3
cipher AES-256-GCM