interface lo
    ip address 5.170.0.102/32

interface eth0
    ip address 10.1.2.1/30

interface eth2
    ip address 10.0.11.5/30

router ospf
    router-id 5.170.0.102
    network 5.170.0.102/32 area 0
    network 10.0.11.4/30 area 0
    exit

mpls ldp
    router-id 5.170.0.102
    ordered-control
    address-family ipv4
        discovery transport-address 5.170.0.102
        interface eth2
        interface lo
        exit-address-family
    exit

router bgp 100
    bgp router-id 5.170.0.102
    neighbor 5.170.0.101 remote-as 100
    neighbor 5.170.0.101 update-source 5.170.0.102
    neighbor 5.170.0.103 remote-as 100
    neighbor 5.170.0.103 update-source 5.170.0.102
    address-family ipv4 unicast
        neighbor 5.170.0.101 next-hop-self
        neighbor 5.170.0.103 next-hop-self
        exit-address-family
    address-family ipv4 vpn
        neighbor 5.170.0.101 activate
        neighbor 5.170.0.101 next-hop-self
        neighbor 5.170.0.103 activate
        neighbor 5.170.0.103 next-hop-self
        exit-address-family
    exit

ip route 192.168.2.0/24 10.1.2.2 vrf vpn10

router bgp 100 vrf vpn10
    # neighbor 10.1.2.2 remote-as 64502
    address-family ipv4 unicast
        redistribute static
        label vpn export auto
        rd vpn export 100:0
        rt vpn both 100:1
        import vpn
        export vpn
        exit-address-family
    exit
