frr version 10.5.0
frr defaults datacenter
hostname R102
log syslog informational
service integrated-vtysh-config
!
interface eth0
 ip address 10.1.2.1/30
exit
!
interface eth1
 ip address 10.0.11.6/30
exit
!
interface eth2
 ip address 10.0.11.9/30
exit
!
interface lo
 ip address 5.170.0.102/32
exit
!
router bgp 100
 bgp router-id 5.170.0.102
 neighbor 5.170.0.101 remote-as 100
 neighbor 5.170.0.101 update-source 5.170.0.102
 neighbor 5.170.0.103 remote-as 100
 neighbor 5.170.0.103 update-source 5.170.0.102
 !
 address-family ipv4 unicast
  neighbor 5.170.0.101 next-hop-self
  neighbor 5.170.0.103 next-hop-self
 exit-address-family
exit
!
router ospf
 ospf router-id 5.170.0.102
 network 5.170.0.102/32 area 0
 network 10.0.11.4/30 area 0
 network 10.0.11.8/30 area 0
 network 10.1.2.0/30 area 0
exit
!